language: clojure
lein: lein2
jdk:
  - openjdk7
  - oraclejdk7
after_script:
  - bash -ex test/coveralls.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3959e95b4c9ff6a297b4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
